AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: sinple_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: sinple_quotes

Layout/LineLength:
  Max: 120
